$(function(){
    var searchOptions = [
        //nfl
        "Arizona Cardinals",
        "Atlanta Falcons",
        "Baltimore Ravens",
        "Buffalo Bills",
        "Carolina Panthers",
        "Chicago Bears",
        "Cincinnati Bengals",
        "Cleveland Browns",
        "Dallas Cowboys",
        "Denver Broncos",
        "Detroit Lions",
        "Green Bay Packers",
        "Houston Texans",
        "Indianapolis Colts",
        "Jacksonville Jaguars",
        "Kansas City Chiefs",
        "Las Vegas Raiders",
        "Los Angeles Chargers",
        "Los Angeles Rams",
        "Miami Dolphins",
        "Minnesota Vikings",
        "New England Patriots",
        "New Orleans Saints",
        "New York Giants",
        "New York Jets",
        "Philadelphia Eagle",
        "Pittsburgh Steeler",
        "San Francisco 49er",
        "Seattle Seahawks",
        "Tampa Bay Buccanee",
        "Tennessee Titans",
        "Washington Command",
        //nba
        "Atlanta Hawks",
        "Boston Celtics",
        "Brooklyn Nets",
        "Charlotte Hornets",
        "Chicago Bulls",
        "Cleveland Cavaliers",
        "Dallas Mavericks",
        "Denver Nuggets",
        "Detroit Pistons",
        "Golden State Warriors",
        "Houston Rockets",
        "Indiana Pacers",
        "Los Angeles Clippers",
        "Los Angeles Lakers",
        "Memphis Grizzlies",
        "Miami Heat",
        "Milwaukee Bucks",
        "Minnesota Timberwolves",
        "New Orleans Pelicans",
        "New York Knicks",
        "Oklahoma City Thunder",
        "Orlando Magic",
        "Philadelphia 76ers",
        "Phoenix Suns",
        "Portland Trail Blazers",
        "Sacramento Kings",
        "San Antonio Spurs",
        "Toronto Raptors",
        "Utah Jazz",
        "Washington Wizards",
        //nhl
        "Anaheim Ducks",
        "Arizona Coyotes",
        "Boston Bruins",
        "Buffalo Sabres",
        "Calgary Flames",
        "Carolina Hurricanes",
        "Chicago Blackhawks",
        "Colorado Avalanche",
        "Columbus Blue Jackets",
        "Dallas Stars",
        "Detroit Red Wings",
        "Edmonton Oilers",
        "Florida Panthers",
        "Los Angeles Kings",
        "Minnesota Wild",
        "Montreal Canadiens",
        "Nashville Predators",
        "New Jersey Devils",
        "New York Islanders",
        "New York Rangers",
        "Ottawa Senators",
        "Philadelphia Flyers",
        "Pittsburgh Penguins",
        "San Jose Sharks",
        "Seattle Kraken",
        "St. Louis Blues",
        "Tampa Bay Lightning",
        "Toronto Maple Leafs",
        "Vancouver Canucks",
        "Vegas Golden Knights",
        "Washington Capitals",
        "Winnipeg Jets",
        //mls
        "Atlanta United FC",
        "Austin FC",
        "Charlotte FC",
        "Chicago Fire FC",
        "Colorado Rapids",
        "Columbus Crew",
        "CF Montreal",
        "D.C. United",
        "FC Cincinnati",
        "FC Dallas",
        "Houston Dynamo FC",
        "Inter Miami CF",
        "LA Galaxy",
        "Los Angeles Football Club",
        "Minnesota United FC",
        "Montreal Impact",
        "Nashville SC",
        "New England Revolution",
        "New York City FC",
        "New York Red Bulls",
        "Orlando City SC",
        "Philadelphia Union",
        "Portland Timbers",
        "Real Salt Lake",
        "San Jose Earthquakes",
        "Seattle Sounders FC",
        "Sporting Kansas City", 
        "Toronto FC",
        "Vancouver Whitecaps FC",
        //artists
        "Taylor Swift",
        "Adele",
        "Billy Joel",
        "Chris Stapleton",
        "Drake",
        "Eagles",
        "Gracie Abrams",
        "Hozier",
        "Kenny Chesney",
        "Levi Turner",
        "Megan Moroney",
        "Morgan Wallen",
        "Olivia Rodrigo",
        "U2",
        "Uncle Kracker",
        "Zac Brown Band",
        "Zach Bryan",
        "Luke Bryan",
        "Luke Combs",
        "Sheryl Crow",
        "Steely Dan",
        "Journey",
        "Def Leppard",
        "Tool",
        "Travis Scott",
        "Isaiah Rashad",
        "Post Malone",
        "Lil Tecca",
        "Phora",
        "Robb Bank$",
        "Rae Sremmurd",
        
    ];
    $("#search").autocomplete({
        source: searchOptions,
    });
});

